### ISSUE TITLE
Segmentation fault with Octave

### ISSUE THREAD

**Issue by schoeps** [mcg1969/vecLibFort#7]
I have issues when compiling Octave 4.0.1rc1 (Mac OS 10.11.2, XCode 7.2, clang-700.1.81). The problem seems to be related to vecLibFort. Compilation works with openblas. Do you have any idea? Thanks.

 liboctave/array/Array.cc-tst ................................ PASS     18/18  
 liboctave/array/CMatrix.cc-tst ..............................
Program received signal SIGSEGV, Segmentation fault.
0x00007fff9697b52e in ?? () from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
(gdb) backtrace
#0  0x00007fff9697b52e in ?? () from /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
#1  0x00007fff5fbf4f40 in ?? ()
#2  0x0000000101e69f40 in zdotu_ () from /usr/local/opt/veclibfort/lib/libvecLibFort.dylib
Backtrace stopped: frame did not save the PC

**Comment by schoeps** [comment]
solved
